# Site settings
name: twinsten
title: Twinsten
description: Data science and machine learning enthusiast
url: https://twinsten.github.io/
baseurl: ''
email: 
cover: https://twinsten.github.io/img/og.png
logo: https://twinsten.github.io/img/emojis/technologist.png
resume: https://twinsten.github.io/resume.pdf
social:
  - title: email
    url: mailto:test@test.com
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: codepen
    url: 
  - title: github
    url: https://github.com/twinsten
  - title: linkedin
    url: 

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
